In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
athletes = pd.read_csv('./athlete_events.csv')
regions = pd.read_csv('./noc_regions.csv')

In [9]:
athletes.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal
0,1,A Dijiang,male,24.0,180.0cm,80.0kg,China,CHN,1992 Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,Male,23.0,170.0cm,60.0kg,China,CHN,2012 Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,Male,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,FeMale,21.0,185.0cm,82.0kg,Netherlands,NED,1988 Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [10]:
regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [11]:
athletes.shape

(271116, 13)

In [12]:
athletes.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 13 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  str
 2   Sex     271116 non-null  str
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  str
 5   Weight  208241 non-null  str
 6   Team    271116 non-null  str
 7   NOC     271116 non-null  str
 8   Games   271116 non-null  str
 9   City    271116 non-null  str
 10  Sport   271116 non-null  str
 11  Event   271116 non-null  str
 12  Medal   39783 non-null   str
dtypes: float64(1), int64(1), str(11)
memory usage: 54.2 MB

In [13]:
athletes.describe()

                  ID            Age
count  271116.000000  261642.000000
mean    68248.954396      25.556898
std     39022.286345       6.393561
min         1.000000      10.000000
25%     34643.000000      21.000000
50%     68205.000000      24.000000
75%    102097.250000      28.000000
max    135571.000000      97.000000

In [16]:
athletes.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [22]:
athletes = athletes.merge(
    regions[['NOC', 'region']],
    on='NOC',
    how='left'
)
athletes.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal,region_x,region_y
0,1,A Dijiang,male,24.0,180.0cm,80.0kg,China,CHN,1992 Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,China
1,2,A Lamusi,Male,23.0,170.0cm,60.0kg,China,CHN,2012 Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,China
2,3,Gunnar Nielsen Aaby,Male,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,Denmark
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,Denmark
4,5,Christine Jacoba Aaftink,FeMale,21.0,185.0cm,82.0kg,Netherlands,NED,1988 Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands,Netherlands

In [26]:
athletes = athletes.drop(columns=['region_x', 'region_y'])
athletes = athletes.merge(
    regions[['NOC', 'region']],
    on='NOC',
    how='left'
)
athletes.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal,region
0,1,A Dijiang,male,24.0,180.0cm,80.0kg,China,CHN,1992 Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China
1,2,A Lamusi,Male,23.0,170.0cm,60.0kg,China,CHN,2012 Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China
2,3,Gunnar Nielsen Aaby,Male,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark
4,5,Christine Jacoba Aaftink,FeMale,21.0,185.0cm,82.0kg,Netherlands,NED,1988 Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands

In [27]:
medalists = athletes[athletes['Medal'].notna()]
medalists.shape

(39783, 14)

In [28]:
medalists.isnull().sum()

ID           0
Name         0
Sex          0
Age        732
Height    8711
Weight    9327
Team         0
NOC          0
Games        0
City         0
Sport        0
Event        0
Medal        0
region       9
dtype: int64

In [29]:
medalists.isnull().mean() * 100

ID         0.000000
Name       0.000000
Sex        0.000000
Age        1.839982
Height    21.896287
Weight    23.444687
Team       0.000000
NOC        0.000000
Games      0.000000
City       0.000000
Sport      0.000000
Event      0.000000
Medal      0.000000
region     0.022623
dtype: float64